USE [master]
GO

/****** Object:  Database [GsbCampagnes]    Script Date: 19/12/2024 09:44:19 ******/
CREATE DATABASE [GsbCampagnes]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GsbCampagnes', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\GsbCampagnes.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GsbCampagnes_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\GsbCampagnes_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GsbCampagnes].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GsbCampagnes] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GsbCampagnes] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GsbCampagnes] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GsbCampagnes] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GsbCampagnes] SET ARITHABORT OFF 
GO

ALTER DATABASE [GsbCampagnes] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [GsbCampagnes] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GsbCampagnes] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GsbCampagnes] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GsbCampagnes] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GsbCampagnes] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GsbCampagnes] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GsbCampagnes] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GsbCampagnes] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GsbCampagnes] SET  ENABLE_BROKER 
GO

ALTER DATABASE [GsbCampagnes] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GsbCampagnes] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GsbCampagnes] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GsbCampagnes] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GsbCampagnes] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GsbCampagnes] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GsbCampagnes] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GsbCampagnes] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [GsbCampagnes] SET  MULTI_USER 
GO

ALTER DATABASE [GsbCampagnes] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GsbCampagnes] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GsbCampagnes] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GsbCampagnes] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GsbCampagnes] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GsbCampagnes] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [GsbCampagnes] SET QUERY_STORE = ON
GO

ALTER DATABASE [GsbCampagnes] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [GsbCampagnes] SET  READ_WRITE 
GO

