//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GsbCampagneDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agence()
        {
            this.AgenceCommunications = new HashSet<AgenceCommunication>();
            this.AgenceEvenementiels = new HashSet<AgenceEvenementiel>();
        }
    
        public int Id { get; set; }
        public string Libelle { get; set; }
        public string Adresse { get; set; }
        public Nullable<int> Telephone { get; set; }
        public string Email { get; set; }
        public string SiteWeb { get; set; }
        public Nullable<int> IdVille { get; set; }
    
        public virtual Ville Ville { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgenceCommunication> AgenceCommunications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgenceEvenementiel> AgenceEvenementiels { get; set; }
    }
}
