//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GsbCampagneDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campagne
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Campagne()
        {
            this.Evenements = new HashSet<Evenement>();
        }
    
        public int Id { get; set; }
        public string Intitule { get; set; }
        public string Objectif { get; set; }
        public Nullable<System.DateTime> DateDebut { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public Nullable<int> IdTypePublic { get; set; }
        public Nullable<int> IdAgenceCommunication { get; set; }
        public Nullable<int> IdAgenceEvenementiel { get; set; }
        public Nullable<int> IdSalarie { get; set; }
    
        public virtual Agence Agence { get; set; }
        public virtual Agence Agence1 { get; set; }
        public virtual Salarie Salarie { get; set; }
        public virtual TypePublic TypePublic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evenement> Evenements { get; set; }
    }
}
