//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GsbCampagneDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GsbCampagnesEntities : DbContext
    {
        public GsbCampagnesEntities()
            : base("name=GsbCampagnesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agence> Agences { get; set; }
        public virtual DbSet<Artiste> Artistes { get; set; }
        public virtual DbSet<Campagne> Campagnes { get; set; }
        public virtual DbSet<CategorieVIP> CategorieVIPs { get; set; }
        public virtual DbSet<CourantArtistique> CourantArtistiques { get; set; }
        public virtual DbSet<Evenement> Evenements { get; set; }
        public virtual DbSet<JournalIntervention> JournalInterventions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Salarie> Salaries { get; set; }
        public virtual DbSet<Theme> Themes { get; set; }
        public virtual DbSet<TypePublic> TypePublics { get; set; }
        public virtual DbSet<Ville> Villes { get; set; }
        public virtual DbSet<VIP> VIPs { get; set; }
        public virtual DbSet<Convier> Conviers { get; set; }
        public virtual DbSet<Participer> Participers { get; set; }
    }
}
