//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GsbCampagneDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campagne
    {
        public int Id { get; set; }
        public string Intitule { get; set; }
        public string Objectif { get; set; }
        public Nullable<System.DateTime> DateDebut { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public Nullable<int> IdTypePublic { get; set; }
        public Nullable<int> IdAgenceCommunication { get; set; }
        public Nullable<int> IdAgenceEvenementiel { get; set; }
        public Nullable<int> IdSalarie { get; set; }
    
        public virtual AgenceCommunication AgenceCommunication { get; set; }
        public virtual AgenceEvenementiel AgenceEvenementiel { get; set; }
        public virtual Salarie Salarie { get; set; }
        public virtual TypePublic TypePublic { get; set; }
    }
}
